/**
 * @file board_config.h
 * @brief Board-Konfiguration für Waveshare ESP32-S3-Touch-LCD-4.3B
 */

#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

// Board Type - Custom Board Definition
#define ESP_PANEL_BOARD_CUSTOM

// LCD Konfiguration
#define ESP_PANEL_USE_LCD
#define ESP_PANEL_LCD_WIDTH 800
#define ESP_PANEL_LCD_HEIGHT 480

// RGB LCD Bus Configuration
#define ESP_PANEL_LCD_BUS_TYPE ESP_PANEL_BUS_TYPE_RGB
#define ESP_PANEL_LCD_RGB_TIMING_FREQ_HZ (16 * 1000 * 1000)
#define ESP_PANEL_LCD_RGB_TIMING_HPW 1
#define ESP_PANEL_LCD_RGB_TIMING_HBP 30
#define ESP_PANEL_LCD_RGB_TIMING_HFP 210
#define ESP_PANEL_LCD_RGB_TIMING_VPW 1
#define ESP_PANEL_LCD_RGB_TIMING_VBP 13
#define ESP_PANEL_LCD_RGB_TIMING_VFP 22

// LCD RGB Pins
#define ESP_PANEL_LCD_RGB_IO_HSYNC 39
#define ESP_PANEL_LCD_RGB_IO_VSYNC 40
#define ESP_PANEL_LCD_RGB_IO_DE 41
#define ESP_PANEL_LCD_RGB_IO_PCLK 42
#define ESP_PANEL_LCD_RGB_IO_DATA0 15  // B0
#define ESP_PANEL_LCD_RGB_IO_DATA1 7   // B1
#define ESP_PANEL_LCD_RGB_IO_DATA2 6   // B2
#define ESP_PANEL_LCD_RGB_IO_DATA3 5   // B3
#define ESP_PANEL_LCD_RGB_IO_DATA4 4   // B4
#define ESP_PANEL_LCD_RGB_IO_DATA5 9   // G0
#define ESP_PANEL_LCD_RGB_IO_DATA6 46  // G1
#define ESP_PANEL_LCD_RGB_IO_DATA7 3   // G2
#define ESP_PANEL_LCD_RGB_IO_DATA8 8   // G3
#define ESP_PANEL_LCD_RGB_IO_DATA9 16  // G4
#define ESP_PANEL_LCD_RGB_IO_DATA10 1  // G5
#define ESP_PANEL_LCD_RGB_IO_DATA11 14 // R0
#define ESP_PANEL_LCD_RGB_IO_DATA12 21 // R1
#define ESP_PANEL_LCD_RGB_IO_DATA13 47 // R2
#define ESP_PANEL_LCD_RGB_IO_DATA14 48 // R3
#define ESP_PANEL_LCD_RGB_IO_DATA15 45 // R4

// Backlight
#define ESP_PANEL_LCD_RGB_IO_BL 2
#define ESP_PANEL_LCD_BL_ON_LEVEL 1

// Touch Konfiguration
#define ESP_PANEL_USE_TOUCH
#define ESP_PANEL_TOUCH_BUS_TYPE ESP_PANEL_BUS_TYPE_I2C
#define ESP_PANEL_TOUCH_NAME GT911

// Touch I2C Configuration
#define ESP_PANEL_TOUCH_I2C_ADDRESS 0x5D
#define ESP_PANEL_TOUCH_I2C_HOST_ID 0
#define ESP_PANEL_TOUCH_I2C_CLK_SPEED_HZ 400000
#define ESP_PANEL_TOUCH_I2C_IO_SCL 20
#define ESP_PANEL_TOUCH_I2C_IO_SDA 19
#define ESP_PANEL_TOUCH_IO_RST 38
#define ESP_PANEL_TOUCH_IO_INT 18

#endif // BOARD_CONFIG_H